// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231016031147_FeedTableVilla")]
    partial class FeedTableVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("fee")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("occupants")
                        .HasColumnType("int");

                    b.Property<int>("squareMeter")
                        .HasColumnType("int");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("urlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amenity = "",
                            creationDate = new DateTime(2023, 10, 15, 21, 11, 47, 280, DateTimeKind.Local).AddTicks(6962),
                            detail = "Detalle de la villa...",
                            fee = 200.0,
                            name = "Villa Real",
                            occupants = 5,
                            squareMeter = 50,
                            updateDate = new DateTime(2023, 10, 15, 21, 11, 47, 280, DateTimeKind.Local).AddTicks(6980),
                            urlImage = ""
                        },
                        new
                        {
                            id = 2,
                            amenity = "",
                            creationDate = new DateTime(2023, 10, 15, 21, 11, 47, 280, DateTimeKind.Local).AddTicks(6987),
                            detail = "Detalle de la villa...",
                            fee = 150.0,
                            name = "Premium vista a la piscina",
                            occupants = 4,
                            squareMeter = 40,
                            updateDate = new DateTime(2023, 10, 15, 21, 11, 47, 280, DateTimeKind.Local).AddTicks(6993),
                            urlImage = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
